### ISSUE TITLE
Colisión con la escalera

### ISSUE THREAD

**Issue by Alex-GameDev** [Special-Kode/College-and-Deans#147]
Prioridad: Media.
Plataforma: Móvil y PC
Descripción: Si intentas llegar a una escalera del final del nivel desde un lateral, en lugar de desde abajo, el personaje no encuentra una ruta correcta hacia la escalera y se bloquea. 
Pasos para reproducirlo: Colocarse justo a la izquierda o a la derecha de la escalera de fin del nivel y pulsar en la escalera.

**Comment by Frollo24** [comment]
Al final hemos conseguido implementar correctamente que el personaje rodee las escaleras antes de subirlas, así que hemos decidido mantener este comportamiento en el juego
