### ISSUE TITLE
Fallo al reescalar en los créditos

### ISSUE THREAD

**Issue by TeklasJr7** [Special-Kode/College-and-Deans#153]
Prioridad/Impacto: Bajo
Plataforma: PC
Descripción: Si juegas en navegador sin estar en modo pantalla completa, la descripción y la imagen de los créditos al pulsar en uno de los integrantes se sale del recuadro que lo delimita ligeramente.
Pasos para reproducirlo: Iniciar el juego sin estar en modo pantalla completa, entrar en el apartado de créditos y seleccionar un integrante.

**Comment by M-Galvez** [comment]
![Error_visual_menus](https://user-images.githubusercontent.com/72497923/143308879-96e41532-22a3-4a73-a027-79c1219fc85a.PNG)

Efectivamente, y además de en los créditos también ocurre en otros menús.
