### ISSUE TITLE
Nivel y Pausa superpuesto

### ISSUE THREAD

**Issue by SaraFuente** [Special-Kode/College-and-Deans#155]
Prioridad o impacto: Impacto bajo.

Plataforma o entorno: Todas las plataformas.

Descripción: Cuando se comienza un nivel, si se es lo suficientemente rápido para abrir el menú de pausa los segundos que el número de nivel está visible en pantalla, se superponen estos dos textos.
![Sin título](https://user-images.githubusercontent.com/61636884/143308483-7f1cb0a4-1f9e-4d24-9560-1dfffdbd0daf.png)

Pasos para reproducirlo:

1.-Desde el principio de cada nivel, abrir el menú de pausa en los segundos que aparece el número de nivel.

**Comment by Frollo24** [comment]
Este comportamiento se produce al tener desordenados los elementos de UI en el proyecto, al reordenarlos queda solucionado. Para la próxima versión estará solucionado.
