### ISSUE TITLE
Problema aspect ratio en IOS

### ISSUE THREAD

**Issue by M-Galvez** [Special-Kode/College-and-Deans#160]
Prioridad o impacto: Impacto medio. 

Plataforma o entorno: IOS.

Descripción: Al ejecutar el juego en IOS y con el dispositivo en vertical, el juego no se adapta a la pantalla de forma adecuada.

Pasos para reproducirlo:  

-Ejecutar el juego en IOS y dejar el dispositivo de forma vertical.

![71111782-fff3-45eb-bb90-86868dcb2db6](https://user-images.githubusercontent.com/72497923/143476181-99c0e90b-a03f-43ce-aa9f-5b7aa81cd869.jpg)

**Comment by Frollo24** [comment]
Hemos estado probando en distintos navegadores y sistemas operativos, y por lo visto depende del navegador y del sistema operativo en el que ejecutas el juego.

En iOS el juego no rota por defecto en ningún navegador y en Android solamente rota por defecto en Brave, Opera y Chrome según lo probado, por lo que esta issue escapa a nuestro alcance.

**Comment by Frollo24** [comment]
Adjuntamos enlaces de interés sobre el tema:

https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation

https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock

https://forum.unity.com/threads/force-landscape-rotation-when-mobile-webgl-is-detected.725927/
